export const STUDENT_LOGIN_STARTED = "STUDENT_LOGIN_STARTED"
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS"
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL"

export const STUDENT_LOGOUT_STARTED = "STUDENT_LOGOUT_STARTED"
export const STUDENT_LOGOUT_SUCCESS = "STUDENT_LOGOUT_SUCCESS"
export const STUDENT_LOGOUT_FAIL = "STUDENT_LOGOUT_FAIL"

export const FETCHING_DATA='DATA_FETCHING_STARTED'
export const DATA_FETCHED='DATA_FETCHING_SUCCESS'
export const FETCHING_FAILED='DATA_FETCHING_FAIL'

export const ANSWER_SUBMISSION_STARTED='ANSWER_SUBMISSION_STARTED'
export const ANSWER_SUBMISSION_SUCCESS='ANSWER_SUBMISSION_SUCCESS'
export const ANSWER_SUBMISSION_FAIL='ANSWER_SUBMISSION_FAIL'

export const GET_ANSWER_STARTED='GET_ANSWER_STARTED'
export const GET_ANSWER_SUBMISSION='GET_ANSWER_SUBMISSION'
export const ANSWER_NOT_FOUND='ANSWER_NOT_FOUND'
export const GET_ANSWER_FAIL='GET_ANSWER_FAIL'

export const FETCH_QUESTION_STARTED='FETCH_QUESTION_STARTED'
export const FETCH_QUESTION_SUCCESS='FETCH_QUESTION_SUCCESS'
export const FETCH_QUESTION_FAIL='FETCH_QUESTION_FAIL'

export const GETALLANSWER_START = 'GETALLANSWER_START'
export const GETALLANSWER_SUCCESS = 'GETALLANSWER_SUCCESS'
export const GETALLANSWER_FAIL = 'GETALLANSWER_FAIL'

export const RESULT_SUBMISSION_STARTED='RESULT_SUBMISSION_STARTED'
export const RESULT_SUBMISSION_SUCCESS='RESULT_SUBMISSION_SUCCESS'
export const RESULT_SUBMISSION_FAIL='RESULT_SUBMISSION_FAIL'

export const REDIRECT = 'REDIRECT'