export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const FETCHING_DATA = 'FETCHING_DATA'
export const DATA_FETCHED = 'DATA_FETCHED'
export const FETCHING_FAILED = 'FETCHING_FAILED'

export const VIEW_EXAM_FETCHING = 'VIEW_EXAM_FETCHING'
export const VIEW_EXAM_FETCHED = 'VIEW_EXAM_FETCHED'
export const VIEW_EXAM_FAILED = 'VIEW_EXAM_FAILED'

export const VIEW_START_DELETING = 'VIEW_START_DELETING'
export const VIEW_ITEM_DELETED = 'VIEW_ITEM_DELETED'
export const VIEW_DELETE_FAILED = 'VIEW_DELETE_FAILED'

export const START_DELETING = 'START_DELETING'
export const ITEM_DELETED = 'ITEM_DELETED'
export const DELETE_FAILED = 'DELETE_FAILED'

export const START_UPDATE = 'START_UPDATE'
export const ITEM_UPDATED = 'ITEM_UPDATED'
export const UPDATE_FAILED = 'UPDATE_FAILED'

export const RESULT_FETCHING = 'RESULT_FETCHING'
export const RESULT_FETCHED = 'RESULT_FETCHED'
export const RESULT_FAILED = 'RESULT_FAILED'

export const RESET_ERROR = 'RESET_ERROR'

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'