export const FETCHING_DATA='FETCHING_DATA'
export const DATA_FEACHED='DATA_FEACHED'
export const FETCHING_FAILED='FETCHING_FAILED'

export const QUESTION_FETCHING='QUESTION_FETCHING'
export const QUESTION_FETCHED='QUESTION_FETCHED'
export const QUESTION_FETCHING_FAIL='QUESTION_FETCHING_FAIL'