export const STUDENT_LOGIN_STARTED = "STUDENT_LOGIN_STARTED"
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS"
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL"

export const STUDENT_LOGOUT_STARTED = "STUDENT_LOGOUT_STARTED"
export const STUDENT_LOGOUT_SUCCESS = "STUDENT_LOGOUT_SUCCESS"
export const STUDENT_LOGOUT_FAIL = "STUDENT_LOGOUT_FAIL"

export const FETCHING_DATA='DATA_FETCHING_STARTED'
export const DATA_FETCHED='DATA_FETCHING_SUCCESS'
export const FETCHING_FAILED='DATA_FETCHING_FAIL'

export const FETCH_QUESTION_STARTED='FETCH_QUESTION_STARTED'
export const FETCH_QUESTION_SUCCESS='FETCH_QUESTION_SUCCESS'
export const FETCH_QUESTION_FAIL='FETCH_QUESTION_FAIL'