export const STUDENT_LOGIN_STARTED = "STUDENT_LOGIN_STARTED"
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS"
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL"

export const STUDENT_LOGOUT_STARTED = "STUDENT_LOGOUT_STARTED"
export const STUDENT_LOGOUT_SUCCESS = "STUDENT_LOGOUT_SUCCESS"
export const STUDENT_LOGOUT_FAIL = "STUDENT_LOGOUT_FAIL"

export const FETCHING_DATA='FETCHING_DATA'
export const DATA_FEACHED='DATA_FEACHED'
export const FETCHING_FAILED='FETCHING_FAILED'

export const FETCH_QUESTION_STARTED='FETCH_QUESTION_STARTED'
export const FETCH_QUESTION_SUCCESS='FETCH_QUESTION_SUCCESS'
export const FETCH_QUESTION_FAIL='FETCH_QUESTION_FAIL'